spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
        exclude: "caches-cache"
      base-path: "/metrics"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    diskspace:
      enabled: true
    defaults:
      enabled: true

logging:
  level:
    ROOT: INFO
  file:
    name: "hw16-log"